---
- name: add epel-release yum repo
  yum:
    name: epel-release
    state: present

- name: install packages for apache
  yum:
    name: [ 'httpd', 'mod_ssl' ]
    state: present

- name: open ports in firewalld
  firewalld:
    port: "{{ item }}"
    immediate: true
    permanent: true
    state: enabled
  with_items: [ '80/tcp', '443/tcp' ]

- name: copy over vhosts.conf from template
  template:
    src: ../../common_templates/vhosts.conf.j2
    dest: /etc/httpd/conf.d/vhosts.conf
  notify: restart apache redhat

- name: copy over ssl.conf from template
  template:
    src: ../../common_templates/ssl.conf.j2
    dest: /etc/httpd/conf.d/ssl.conf
  notify: restart apache redhat
