---
- name: install Java JDK 8
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: install Java Cryptography Extension (JCE) file US_export_policy.jar
  copy:
    src: jce-US_export_policy.jar
    dest: /usr/lib/jvm/jre/lib/security/US_export_policy.jar

- name: install Java Cryptography Extension (JCE) file local_policy.jar
  copy:
    src: jce-local_policy.jar
    dest: /usr/lib/jvm/jre/lib/security/local_policy.jar

- name: create tomcat group
  group:
    name: tomcat
    state: present

- name: create tomcat user
  user:
    name: tomcat
    group: tomcat

- name: download and extract tomcat
  unarchive:
    src: http://mirrors.advancedhosters.com/apache/tomcat/tomcat-8/v8.5.23/bin/apache-tomcat-8.5.23.tar.gz
    dest: /opt/tomcat-8.5.23
    remote_src: yes
    owner: tomcat
    group: tomcat

- name: create /opt/tomcat symlink
  file:
    name: /opt/tomcat
    src: /opt/tomcat-8.5.23
    state: link

- name: create systemd unit file for tomcat
  copy:
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service

- name: start tomcat service
  service:
    name: tomcat
    state: started

- name: install midPoint
  unarchive:
    src: http://www.evolveum.com/downloads/midpoint/3.6.1/midpoint-3.6.1-dist.tar.gz
    dest: /tmp/
    remote_src: yes

- name: create midPoint home
  file:
    state: directory
    path: /opt/midpoint

# - name: modify setenv.sh
# - name: modify server.xml
# - name: stop tomcat
# - name: deploy midPoint warfile
# - name: start tomcat
# - name: open ports in firewall
