---
- name: create tomcat group
  group:
    name: tomcat
    state: present

- name: create tomcat user
  user:
    name: tomcat
    group: tomcat

- name: download and extract tomcat
  unarchive:
    src: http://mirrors.advancedhosters.com/apache/tomcat/tomcat-8/v8.5.23/bin/apache-tomcat-8.5.23.tar.gz
    dest: /opt
    remote_src: yes
    owner: tomcat
    group: tomcat
    creates: /opt/apache-tomcat-8.5.23/bin/catalina.sh

- name: create /opt/tomcat symlink
  file:
    name: /opt/tomcat
    src: /opt/apache-tomcat-8.5.23
    state: link

- name: create systemd unit file for tomcat
  copy:
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service

- name: start tomcat service
  service:
    name: tomcat
    state: started

- name: open ports in firewalld
  firewalld:
    port: "8080/tcp"
    immediate: true
    permanent: true
    state: enabled
