---
- name: install midPoint
  unarchive:
    src: http://www.evolveum.com/downloads/midpoint/3.6.1/midpoint-3.6.1-dist.tar.gz
    dest: /tmp/
    remote_src: yes

- name: create midPoint home
  file:
    state: directory
    path: /opt/midpoint
    owner: tomcat
    group: tomcat

- name: modify setenv.sh
  blockinfile:
    dest: /opt/tomcat/bin/setenv.sh
    create: yes
    block: |
      MIDPOINT_HOME="/opt/midpoint/"
      JAVA_OPTS="$JAVA_OPTS -Dmidpoint.home=$MIDPOINT_HOME -Djavax.net.ssl.trustStore=$MIDPOINT_HOME/keystore.jceks -Djavax.net.ssl.trustStoreType=jceks -server -Xms512m -Xmx2048m"
      export MIDPOINT_HOME JAVA_OPTS
    marker: "# {mark} ANSIBLE MANAGED BLOCK: midpoint"
    owner: tomcat
    group: tomcat
    mode: 0750

- name: copy over modified server.xml
  copy:
    src: tomcat-server.xml
    dest: /opt/tomcat/conf/server.xml

- name: stop tomcat
  service:
    name: tomcat
    state: stopped

- name: deploy midPoint warfile
  copy:
    src: /tmp/midpoint-3.6.1/war/midpoint.war
    remote_src: yes
    dest: /opt/tomcat/webapps

- name: start tomcat
  service:
    name: tomcat
    state: started

- name: wait for midPoint to start
  local_action: uri url=http://{{ inventory_hostname }}:8080/midpoint return_content=true status_code=200
  register: midpoint_site
  until: "'2010-2017' in midpoint_site.content"
  retries: 10
  delay: 60
