---
- name: add epel-release yum repo
  yum:
    name: epel-release
    state: present

- name: install packages for apache and SSL
  yum:
    name: [ 'httpd', 'mod_ssl', 'gcc', 'httpd-devel' ]
    state: present

- name: open ports in firewalld
  firewalld:
    port: "{{ item }}"
    immediate: true
    permanent: true
    state: enabled
  with_items: [ '80/tcp', '443/tcp' ]

- name: close port 8080 in firewalld
  firewalld:
    port: "8080/tcp"
    immediate: true
    permanent: true
    state: disabled

- name: download Apache Tomcat Connector JK
  unarchive:
    src: http://apache.osuosl.org/tomcat/tomcat-connectors/jk/tomcat-connectors-1.2.42-src.tar.gz
    remote_src: yes
    dest: /tmp

- name: configure Apache Tomcat Connector JK
  command: ./configure --with-apxs=/usr/bin/apxs
  args:
    chdir: /tmp/tomcat-connectors-1.2.42-src/native
    creates: /tmp/tomcat-connectors-1.2.42-src/native/Makefile

- name: build Apache Tomcat Connector JK
  command: make
  args:
    chdir: /tmp/tomcat-connectors-1.2.42-src/native
    creates: /tmp/tomcat-connectors-1.2.42-src/native/apache-2.0/mod_jk.so

- name: install Apache Tomcat Connector JK
  command: make install
  args:
    chdir: /tmp/tomcat-connectors-1.2.42-src/native
    creates: /etc/httpd/modules/mod_jk.so

- name: copy over jk.conf file
  copy:
    src: jk.conf
    dest: /etc/httpd/conf.d/jk.conf

- name: copy over workers.properties file
  copy:
    src: jk-workers.properties
    dest: /etc/httpd/conf/workers.properties

- name: copy over ssl.conf from template
  template:
    src: apache-ssl.conf.j2
    dest: /etc/httpd/conf.d/ssl.conf

- name: copy over no-ssl.conf from template
  template:
    src: apache-no-ssl.conf.j2
    dest: /etc/httpd/conf.d/no-ssl.conf

- debug:
    msg: "IMPORTANT! You must copy your SSL cert files to the target host and restart Apache before SSL will work!"
