---
- name: create midpoint group
  group:
    name: midpoint
    state: present

- name: create midpoint user
  user:
    name: midpoint
    group: midpoint

- name: create ansible remote_tmp dir
  file:
    dest: $HOME/.ansible/tmp
    state: directory
    owner: midpoint
    group: midpoint

- name: install midPoint
  unarchive:
    src: https://evolveum.com/downloads/midpoint/3.8/midpoint-3.8-dist.tar.gz
    dest: /opt/
    remote_src: yes
    owner: midpoint
    group: midpoint
    creates: /opt/midpoint-3.8/bin/start.sh

- name: make midpoint owner of midPoint home
  file:
    dest: /opt/midpoint-3.8
    state: directory
    owner: midpoint
    group: midpoint
    recurse: yes

- name: create /opt/midpoint symlink
  file:
    name: /opt/midpoint
    src: /opt/midpoint-3.8
    state: link

- name: set 'is_first_run' flag to default value
  set_fact:
    is_first_run: true

- name: stat var/ directory in MIDPOINT_HOME
  stat:
    path: /opt/midpoint/var
  register: var

- name: unset 'is_first_run' if var/ exists
  set_fact:
    is_first_run: false
  when: var.stat.isdir is defined and var.stat.isdir

- name: create var/ in MIDPOINT_HOME
  file:
    dest: /opt/midpoint/var
    state: directory
    owner: midpoint
    group: midpoint
  when: is_first_run

- name: configure application.yml
  copy:
    src: ../../common_files/application.yml
    dest: /opt/midpoint/var/application.yml
    owner: midpoint
    group: midpoint

- name: start midPoint
  shell: /opt/midpoint/bin/start.sh
  become: yes
  become_user: midpoint
  when: is_first_run
  tags:
    # disable ansible-lint check for this task because it's too strict about shell commands
    - skip_ansible_lint

- name: wait for port 8080 to come up
  wait_for:
    port: 8080
    delay: 10

- name: wait for midPoint to start
  uri: url=http://127.0.0.1:8080 return_content=true status_code=200
  register: midpoint_site
  until: "'2010-2018' in midpoint_site.content"
  retries: 10
  when: is_first_run

- name: stop midPoint
  shell: /opt/midpoint/bin/stop.sh
  become: yes
  become_user: midpoint
  when: is_first_run
  tags:
    # disable ansible-lint check for this task because it's too strict about shell commands
    - skip_ansible_lint

- name: create systemd unit file for midPoint
  template:
    src: ../../common_templates/midpoint.service.j2
    dest: /etc/systemd/system/midpoint.service

- name: start midpoint service
  service:
    name: midpoint
    state: started

- name: wait for port 8080 to come up
  wait_for:
    port: 8080
    delay: 10

- name: wait for midPoint service to start
  uri: url=http://127.0.0.1:8080 return_content=true status_code=200
  register: midpoint_site
  until: "'2010-2018' in midpoint_site.content"
  retries: 10
  when: is_first_run
