---
- import_tasks: install_java_redhat.yml
  when: ansible_os_family == 'RedHat'
- import_tasks: install_tomcat_redhat.yml
  when: ansible_os_family == 'RedHat'
- import_tasks: install_midpoint.yml
- import_tasks: setup_mariadb.yml
  when: midpoint.mariadb is defined
- import_tasks: install_apache_redhat.yml
  when: midpoint.use_apache_ssl and ansible_os_family == 'RedHat'
