---
# install java
- include_tasks: install_java_redhat.yml
  when: ansible_os_family == 'RedHat'

# install standalone midPoint
- import_tasks: install_standalone_midpoint.yml

# install Apache
- include_tasks: install_standalone_apache_redhat.yml
  when: ansible_os_family == 'RedHat'

# setup mariadb database
- include_tasks: setup_local_mariadb.yml
  when: midpoint.mariadb is defined and midpoint.mariadb.use_local_db
- include_tasks: use_external_mariadb.yml
  when: midpoint.mariadb is defined and not midpoint.mariadb.use_local_db

# post-install tasks
- import_tasks: post_install.yml
